-- Auto-generated from docs/subjects_master_import_template.csv
-- Restore: psql -f scripts/seed-subjects-master.sql  (requires pgcrypto for gen_random_uuid on older PG)
DELETE FROM admissions.subjects_master;
INSERT INTO admissions.subjects_master ("Id", "BoardCode", "StreamCode", "SubjectName", "SortOrder", "IsActive") VALUES (gen_random_uuid(), 'MBOSE', 'ARTS', 'English', 10, true);
INSERT INTO admissions.subjects_master ("Id", "BoardCode", "StreamCode", "SubjectName", "SortOrder", "IsActive") VALUES (gen_random_uuid(), 'MBOSE', 'ARTS', 'Alternative English', 20, true);
INSERT INTO admissions.subjects_master ("Id", "BoardCode", "StreamCode", "SubjectName", "SortOrder", "IsActive") VALUES (gen_random_uuid(), 'MBOSE', 'ARTS', 'Garo (MIL)', 30, true);
INSERT INTO admissions.subjects_master ("Id", "BoardCode", "StreamCode", "SubjectName", "SortOrder", "IsActive") VALUES (gen_random_uuid(), 'MBOSE', 'ARTS', 'Elective Garo', 40, true);
INSERT INTO admissions.subjects_master ("Id", "BoardCode", "StreamCode", "SubjectName", "SortOrder", "IsActive") VALUES (gen_random_uuid(), 'MBOSE', 'ARTS', 'Education', 50, true);
INSERT INTO admissions.subjects_master ("Id", "BoardCode", "StreamCode", "SubjectName", "SortOrder", "IsActive") VALUES (gen_random_uuid(), 'MBOSE', 'ARTS', 'Economics', 60, true);
INSERT INTO admissions.subjects_master ("Id", "BoardCode", "StreamCode", "SubjectName", "SortOrder", "IsActive") VALUES (gen_random_uuid(), 'MBOSE', 'ARTS', 'History', 70, true);
INSERT INTO admissions.subjects_master ("Id", "BoardCode", "StreamCode", "SubjectName", "SortOrder", "IsActive") VALUES (gen_random_uuid(), 'MBOSE', 'ARTS', 'Political Science', 80, true);
INSERT INTO admissions.subjects_master ("Id", "BoardCode", "StreamCode", "SubjectName", "SortOrder", "IsActive") VALUES (gen_random_uuid(), 'MBOSE', 'ARTS', 'Sociology', 90, true);
INSERT INTO admissions.subjects_master ("Id", "BoardCode", "StreamCode", "SubjectName", "SortOrder", "IsActive") VALUES (gen_random_uuid(), 'MBOSE', 'ARTS', 'Geography', 100, true);
INSERT INTO admissions.subjects_master ("Id", "BoardCode", "StreamCode", "SubjectName", "SortOrder", "IsActive") VALUES (gen_random_uuid(), 'MBOSE', 'ARTS', 'Philosophy', 110, true);
INSERT INTO admissions.subjects_master ("Id", "BoardCode", "StreamCode", "SubjectName", "SortOrder", "IsActive") VALUES (gen_random_uuid(), 'MBOSE', 'ARTS', 'Psychology', 120, true);
INSERT INTO admissions.subjects_master ("Id", "BoardCode", "StreamCode", "SubjectName", "SortOrder", "IsActive") VALUES (gen_random_uuid(), 'MBOSE', 'ARTS', 'Mathematics', 130, true);
INSERT INTO admissions.subjects_master ("Id", "BoardCode", "StreamCode", "SubjectName", "SortOrder", "IsActive") VALUES (gen_random_uuid(), 'MBOSE', 'ARTS', 'Khasi (MIL)', 140, true);
INSERT INTO admissions.subjects_master ("Id", "BoardCode", "StreamCode", "SubjectName", "SortOrder", "IsActive") VALUES (gen_random_uuid(), 'MBOSE', 'ARTS', 'Mizo (MIL)', 150, true);
INSERT INTO admissions.subjects_master ("Id", "BoardCode", "StreamCode", "SubjectName", "SortOrder", "IsActive") VALUES (gen_random_uuid(), 'MBOSE', 'ARTS', 'Hindi (MIL)', 160, true);
INSERT INTO admissions.subjects_master ("Id", "BoardCode", "StreamCode", "SubjectName", "SortOrder", "IsActive") VALUES (gen_random_uuid(), 'MBOSE', 'ARTS', 'Bengali (MIL)', 170, true);
INSERT INTO admissions.subjects_master ("Id", "BoardCode", "StreamCode", "SubjectName", "SortOrder", "IsActive") VALUES (gen_random_uuid(), 'MBOSE', 'ARTS', 'Assamese (MIL)', 180, true);
INSERT INTO admissions.subjects_master ("Id", "BoardCode", "StreamCode", "SubjectName", "SortOrder", "IsActive") VALUES (gen_random_uuid(), 'MBOSE', 'ARTS', 'Nepali (MIL)', 190, true);
INSERT INTO admissions.subjects_master ("Id", "BoardCode", "StreamCode", "SubjectName", "SortOrder", "IsActive") VALUES (gen_random_uuid(), 'MBOSE', 'SCIENCE', 'English', 10, true);
INSERT INTO admissions.subjects_master ("Id", "BoardCode", "StreamCode", "SubjectName", "SortOrder", "IsActive") VALUES (gen_random_uuid(), 'MBOSE', 'SCIENCE', 'Physics', 20, true);
INSERT INTO admissions.subjects_master ("Id", "BoardCode", "StreamCode", "SubjectName", "SortOrder", "IsActive") VALUES (gen_random_uuid(), 'MBOSE', 'SCIENCE', 'Chemistry', 30, true);
INSERT INTO admissions.subjects_master ("Id", "BoardCode", "StreamCode", "SubjectName", "SortOrder", "IsActive") VALUES (gen_random_uuid(), 'MBOSE', 'SCIENCE', 'Mathematics', 40, true);
INSERT INTO admissions.subjects_master ("Id", "BoardCode", "StreamCode", "SubjectName", "SortOrder", "IsActive") VALUES (gen_random_uuid(), 'MBOSE', 'SCIENCE', 'Biology', 50, true);
INSERT INTO admissions.subjects_master ("Id", "BoardCode", "StreamCode", "SubjectName", "SortOrder", "IsActive") VALUES (gen_random_uuid(), 'MBOSE', 'SCIENCE', 'Computer Science', 60, true);
INSERT INTO admissions.subjects_master ("Id", "BoardCode", "StreamCode", "SubjectName", "SortOrder", "IsActive") VALUES (gen_random_uuid(), 'MBOSE', 'SCIENCE', 'Environmental Science', 70, true);
INSERT INTO admissions.subjects_master ("Id", "BoardCode", "StreamCode", "SubjectName", "SortOrder", "IsActive") VALUES (gen_random_uuid(), 'MBOSE', 'SCIENCE', 'Khasi (MIL)', 80, true);
INSERT INTO admissions.subjects_master ("Id", "BoardCode", "StreamCode", "SubjectName", "SortOrder", "IsActive") VALUES (gen_random_uuid(), 'MBOSE', 'SCIENCE', 'Mizo (MIL)', 90, true);
INSERT INTO admissions.subjects_master ("Id", "BoardCode", "StreamCode", "SubjectName", "SortOrder", "IsActive") VALUES (gen_random_uuid(), 'MBOSE', 'SCIENCE', 'Hindi (MIL)', 100, true);
INSERT INTO admissions.subjects_master ("Id", "BoardCode", "StreamCode", "SubjectName", "SortOrder", "IsActive") VALUES (gen_random_uuid(), 'MBOSE', 'SCIENCE', 'Bengali (MIL)', 110, true);
INSERT INTO admissions.subjects_master ("Id", "BoardCode", "StreamCode", "SubjectName", "SortOrder", "IsActive") VALUES (gen_random_uuid(), 'MBOSE', 'SCIENCE', 'Assamese (MIL)', 120, true);
INSERT INTO admissions.subjects_master ("Id", "BoardCode", "StreamCode", "SubjectName", "SortOrder", "IsActive") VALUES (gen_random_uuid(), 'MBOSE', 'SCIENCE', 'Nepali (MIL)', 130, true);
INSERT INTO admissions.subjects_master ("Id", "BoardCode", "StreamCode", "SubjectName", "SortOrder", "IsActive") VALUES (gen_random_uuid(), 'MBOSE', 'COMMERCE', 'English', 10, true);
INSERT INTO admissions.subjects_master ("Id", "BoardCode", "StreamCode", "SubjectName", "SortOrder", "IsActive") VALUES (gen_random_uuid(), 'MBOSE', 'COMMERCE', 'Accountancy', 20, true);
INSERT INTO admissions.subjects_master ("Id", "BoardCode", "StreamCode", "SubjectName", "SortOrder", "IsActive") VALUES (gen_random_uuid(), 'MBOSE', 'COMMERCE', 'Business Studies', 30, true);
INSERT INTO admissions.subjects_master ("Id", "BoardCode", "StreamCode", "SubjectName", "SortOrder", "IsActive") VALUES (gen_random_uuid(), 'MBOSE', 'COMMERCE', 'Economics', 40, true);
INSERT INTO admissions.subjects_master ("Id", "BoardCode", "StreamCode", "SubjectName", "SortOrder", "IsActive") VALUES (gen_random_uuid(), 'MBOSE', 'COMMERCE', 'Mathematics', 50, true);
INSERT INTO admissions.subjects_master ("Id", "BoardCode", "StreamCode", "SubjectName", "SortOrder", "IsActive") VALUES (gen_random_uuid(), 'MBOSE', 'COMMERCE', 'Computer Science', 60, true);
INSERT INTO admissions.subjects_master ("Id", "BoardCode", "StreamCode", "SubjectName", "SortOrder", "IsActive") VALUES (gen_random_uuid(), 'MBOSE', 'COMMERCE', 'Entrepreneurship', 70, true);
INSERT INTO admissions.subjects_master ("Id", "BoardCode", "StreamCode", "SubjectName", "SortOrder", "IsActive") VALUES (gen_random_uuid(), 'MBOSE', 'COMMERCE', 'Khasi (MIL)', 80, true);
INSERT INTO admissions.subjects_master ("Id", "BoardCode", "StreamCode", "SubjectName", "SortOrder", "IsActive") VALUES (gen_random_uuid(), 'MBOSE', 'COMMERCE', 'Mizo (MIL)', 90, true);
INSERT INTO admissions.subjects_master ("Id", "BoardCode", "StreamCode", "SubjectName", "SortOrder", "IsActive") VALUES (gen_random_uuid(), 'MBOSE', 'COMMERCE', 'Hindi (MIL)', 100, true);
INSERT INTO admissions.subjects_master ("Id", "BoardCode", "StreamCode", "SubjectName", "SortOrder", "IsActive") VALUES (gen_random_uuid(), 'MBOSE', 'COMMERCE', 'Bengali (MIL)', 110, true);
INSERT INTO admissions.subjects_master ("Id", "BoardCode", "StreamCode", "SubjectName", "SortOrder", "IsActive") VALUES (gen_random_uuid(), 'MBOSE', 'COMMERCE', 'Assamese (MIL)', 120, true);
INSERT INTO admissions.subjects_master ("Id", "BoardCode", "StreamCode", "SubjectName", "SortOrder", "IsActive") VALUES (gen_random_uuid(), 'MBOSE', 'COMMERCE', 'Nepali (MIL)', 130, true);
INSERT INTO admissions.subjects_master ("Id", "BoardCode", "StreamCode", "SubjectName", "SortOrder", "IsActive") VALUES (gen_random_uuid(), 'CBSE', 'ARTS', 'English Core', 10, true);
INSERT INTO admissions.subjects_master ("Id", "BoardCode", "StreamCode", "SubjectName", "SortOrder", "IsActive") VALUES (gen_random_uuid(), 'CBSE', 'ARTS', 'English Elective', 20, true);
INSERT INTO admissions.subjects_master ("Id", "BoardCode", "StreamCode", "SubjectName", "SortOrder", "IsActive") VALUES (gen_random_uuid(), 'CBSE', 'ARTS', 'History', 30, true);
INSERT INTO admissions.subjects_master ("Id", "BoardCode", "StreamCode", "SubjectName", "SortOrder", "IsActive") VALUES (gen_random_uuid(), 'CBSE', 'ARTS', 'Political Science', 40, true);
INSERT INTO admissions.subjects_master ("Id", "BoardCode", "StreamCode", "SubjectName", "SortOrder", "IsActive") VALUES (gen_random_uuid(), 'CBSE', 'ARTS', 'Geography', 50, true);
INSERT INTO admissions.subjects_master ("Id", "BoardCode", "StreamCode", "SubjectName", "SortOrder", "IsActive") VALUES (gen_random_uuid(), 'CBSE', 'ARTS', 'Economics', 60, true);
INSERT INTO admissions.subjects_master ("Id", "BoardCode", "StreamCode", "SubjectName", "SortOrder", "IsActive") VALUES (gen_random_uuid(), 'CBSE', 'ARTS', 'Sociology', 70, true);
INSERT INTO admissions.subjects_master ("Id", "BoardCode", "StreamCode", "SubjectName", "SortOrder", "IsActive") VALUES (gen_random_uuid(), 'CBSE', 'ARTS', 'Psychology', 80, true);
INSERT INTO admissions.subjects_master ("Id", "BoardCode", "StreamCode", "SubjectName", "SortOrder", "IsActive") VALUES (gen_random_uuid(), 'CBSE', 'ARTS', 'Philosophy', 90, true);
INSERT INTO admissions.subjects_master ("Id", "BoardCode", "StreamCode", "SubjectName", "SortOrder", "IsActive") VALUES (gen_random_uuid(), 'CBSE', 'ARTS', 'Physical Education', 100, true);
INSERT INTO admissions.subjects_master ("Id", "BoardCode", "StreamCode", "SubjectName", "SortOrder", "IsActive") VALUES (gen_random_uuid(), 'CBSE', 'ARTS', 'Fine Arts', 110, true);
INSERT INTO admissions.subjects_master ("Id", "BoardCode", "StreamCode", "SubjectName", "SortOrder", "IsActive") VALUES (gen_random_uuid(), 'CBSE', 'ARTS', 'Home Science', 120, true);
INSERT INTO admissions.subjects_master ("Id", "BoardCode", "StreamCode", "SubjectName", "SortOrder", "IsActive") VALUES (gen_random_uuid(), 'CBSE', 'ARTS', 'Mathematics', 130, true);
INSERT INTO admissions.subjects_master ("Id", "BoardCode", "StreamCode", "SubjectName", "SortOrder", "IsActive") VALUES (gen_random_uuid(), 'CBSE', 'ARTS', 'Hindi', 140, true);
INSERT INTO admissions.subjects_master ("Id", "BoardCode", "StreamCode", "SubjectName", "SortOrder", "IsActive") VALUES (gen_random_uuid(), 'CBSE', 'SCIENCE', 'English', 10, true);
INSERT INTO admissions.subjects_master ("Id", "BoardCode", "StreamCode", "SubjectName", "SortOrder", "IsActive") VALUES (gen_random_uuid(), 'CBSE', 'SCIENCE', 'Physics', 20, true);
INSERT INTO admissions.subjects_master ("Id", "BoardCode", "StreamCode", "SubjectName", "SortOrder", "IsActive") VALUES (gen_random_uuid(), 'CBSE', 'SCIENCE', 'Chemistry', 30, true);
INSERT INTO admissions.subjects_master ("Id", "BoardCode", "StreamCode", "SubjectName", "SortOrder", "IsActive") VALUES (gen_random_uuid(), 'CBSE', 'SCIENCE', 'Mathematics', 40, true);
INSERT INTO admissions.subjects_master ("Id", "BoardCode", "StreamCode", "SubjectName", "SortOrder", "IsActive") VALUES (gen_random_uuid(), 'CBSE', 'SCIENCE', 'Biology', 50, true);
INSERT INTO admissions.subjects_master ("Id", "BoardCode", "StreamCode", "SubjectName", "SortOrder", "IsActive") VALUES (gen_random_uuid(), 'CBSE', 'SCIENCE', 'Computer Science', 60, true);
INSERT INTO admissions.subjects_master ("Id", "BoardCode", "StreamCode", "SubjectName", "SortOrder", "IsActive") VALUES (gen_random_uuid(), 'CBSE', 'SCIENCE', 'Informatics Practices', 70, true);
INSERT INTO admissions.subjects_master ("Id", "BoardCode", "StreamCode", "SubjectName", "SortOrder", "IsActive") VALUES (gen_random_uuid(), 'CBSE', 'SCIENCE', 'Physical Education', 80, true);
INSERT INTO admissions.subjects_master ("Id", "BoardCode", "StreamCode", "SubjectName", "SortOrder", "IsActive") VALUES (gen_random_uuid(), 'CBSE', 'SCIENCE', 'Hindi', 140, true);
INSERT INTO admissions.subjects_master ("Id", "BoardCode", "StreamCode", "SubjectName", "SortOrder", "IsActive") VALUES (gen_random_uuid(), 'CBSE', 'COMMERCE', 'English', 10, true);
INSERT INTO admissions.subjects_master ("Id", "BoardCode", "StreamCode", "SubjectName", "SortOrder", "IsActive") VALUES (gen_random_uuid(), 'CBSE', 'COMMERCE', 'Accountancy', 20, true);
INSERT INTO admissions.subjects_master ("Id", "BoardCode", "StreamCode", "SubjectName", "SortOrder", "IsActive") VALUES (gen_random_uuid(), 'CBSE', 'COMMERCE', 'Business Studies', 30, true);
INSERT INTO admissions.subjects_master ("Id", "BoardCode", "StreamCode", "SubjectName", "SortOrder", "IsActive") VALUES (gen_random_uuid(), 'CBSE', 'COMMERCE', 'Economics', 40, true);
INSERT INTO admissions.subjects_master ("Id", "BoardCode", "StreamCode", "SubjectName", "SortOrder", "IsActive") VALUES (gen_random_uuid(), 'CBSE', 'COMMERCE', 'Mathematics', 50, true);
INSERT INTO admissions.subjects_master ("Id", "BoardCode", "StreamCode", "SubjectName", "SortOrder", "IsActive") VALUES (gen_random_uuid(), 'CBSE', 'COMMERCE', 'Applied Mathematics', 60, true);
INSERT INTO admissions.subjects_master ("Id", "BoardCode", "StreamCode", "SubjectName", "SortOrder", "IsActive") VALUES (gen_random_uuid(), 'CBSE', 'COMMERCE', 'Informatics Practices', 70, true);
INSERT INTO admissions.subjects_master ("Id", "BoardCode", "StreamCode", "SubjectName", "SortOrder", "IsActive") VALUES (gen_random_uuid(), 'CBSE', 'COMMERCE', 'Entrepreneurship', 80, true);
INSERT INTO admissions.subjects_master ("Id", "BoardCode", "StreamCode", "SubjectName", "SortOrder", "IsActive") VALUES (gen_random_uuid(), 'CBSE', 'COMMERCE', 'Hindi', 140, true);
INSERT INTO admissions.subjects_master ("Id", "BoardCode", "StreamCode", "SubjectName", "SortOrder", "IsActive") VALUES (gen_random_uuid(), 'ISC', 'ARTS', 'English', 10, true);
INSERT INTO admissions.subjects_master ("Id", "BoardCode", "StreamCode", "SubjectName", "SortOrder", "IsActive") VALUES (gen_random_uuid(), 'ISC', 'ARTS', 'History', 20, true);
INSERT INTO admissions.subjects_master ("Id", "BoardCode", "StreamCode", "SubjectName", "SortOrder", "IsActive") VALUES (gen_random_uuid(), 'ISC', 'ARTS', 'Political Science', 30, true);
INSERT INTO admissions.subjects_master ("Id", "BoardCode", "StreamCode", "SubjectName", "SortOrder", "IsActive") VALUES (gen_random_uuid(), 'ISC', 'ARTS', 'Sociology', 40, true);
INSERT INTO admissions.subjects_master ("Id", "BoardCode", "StreamCode", "SubjectName", "SortOrder", "IsActive") VALUES (gen_random_uuid(), 'ISC', 'ARTS', 'Psychology', 50, true);
INSERT INTO admissions.subjects_master ("Id", "BoardCode", "StreamCode", "SubjectName", "SortOrder", "IsActive") VALUES (gen_random_uuid(), 'ISC', 'ARTS', 'Geography', 60, true);
INSERT INTO admissions.subjects_master ("Id", "BoardCode", "StreamCode", "SubjectName", "SortOrder", "IsActive") VALUES (gen_random_uuid(), 'ISC', 'ARTS', 'Economics', 70, true);
INSERT INTO admissions.subjects_master ("Id", "BoardCode", "StreamCode", "SubjectName", "SortOrder", "IsActive") VALUES (gen_random_uuid(), 'ISC', 'ARTS', 'Home Science', 80, true);
INSERT INTO admissions.subjects_master ("Id", "BoardCode", "StreamCode", "SubjectName", "SortOrder", "IsActive") VALUES (gen_random_uuid(), 'ISC', 'ARTS', 'Environmental Science', 90, true);
INSERT INTO admissions.subjects_master ("Id", "BoardCode", "StreamCode", "SubjectName", "SortOrder", "IsActive") VALUES (gen_random_uuid(), 'ISC', 'ARTS', 'Physical Education', 100, true);
INSERT INTO admissions.subjects_master ("Id", "BoardCode", "StreamCode", "SubjectName", "SortOrder", "IsActive") VALUES (gen_random_uuid(), 'ISC', 'ARTS', 'Hindi', 110, true);
INSERT INTO admissions.subjects_master ("Id", "BoardCode", "StreamCode", "SubjectName", "SortOrder", "IsActive") VALUES (gen_random_uuid(), 'ISC', 'SCIENCE', 'English', 10, true);
INSERT INTO admissions.subjects_master ("Id", "BoardCode", "StreamCode", "SubjectName", "SortOrder", "IsActive") VALUES (gen_random_uuid(), 'ISC', 'SCIENCE', 'Physics', 20, true);
INSERT INTO admissions.subjects_master ("Id", "BoardCode", "StreamCode", "SubjectName", "SortOrder", "IsActive") VALUES (gen_random_uuid(), 'ISC', 'SCIENCE', 'Chemistry', 30, true);
INSERT INTO admissions.subjects_master ("Id", "BoardCode", "StreamCode", "SubjectName", "SortOrder", "IsActive") VALUES (gen_random_uuid(), 'ISC', 'SCIENCE', 'Mathematics', 40, true);
INSERT INTO admissions.subjects_master ("Id", "BoardCode", "StreamCode", "SubjectName", "SortOrder", "IsActive") VALUES (gen_random_uuid(), 'ISC', 'SCIENCE', 'Biology', 50, true);
INSERT INTO admissions.subjects_master ("Id", "BoardCode", "StreamCode", "SubjectName", "SortOrder", "IsActive") VALUES (gen_random_uuid(), 'ISC', 'SCIENCE', 'Computer Science', 60, true);
INSERT INTO admissions.subjects_master ("Id", "BoardCode", "StreamCode", "SubjectName", "SortOrder", "IsActive") VALUES (gen_random_uuid(), 'ISC', 'SCIENCE', 'Environmental Science', 70, true);
INSERT INTO admissions.subjects_master ("Id", "BoardCode", "StreamCode", "SubjectName", "SortOrder", "IsActive") VALUES (gen_random_uuid(), 'ISC', 'SCIENCE', 'Hindi', 80, true);
INSERT INTO admissions.subjects_master ("Id", "BoardCode", "StreamCode", "SubjectName", "SortOrder", "IsActive") VALUES (gen_random_uuid(), 'ISC', 'COMMERCE', 'English', 10, true);
INSERT INTO admissions.subjects_master ("Id", "BoardCode", "StreamCode", "SubjectName", "SortOrder", "IsActive") VALUES (gen_random_uuid(), 'ISC', 'COMMERCE', 'Accounts', 20, true);
INSERT INTO admissions.subjects_master ("Id", "BoardCode", "StreamCode", "SubjectName", "SortOrder", "IsActive") VALUES (gen_random_uuid(), 'ISC', 'COMMERCE', 'Commerce', 30, true);
INSERT INTO admissions.subjects_master ("Id", "BoardCode", "StreamCode", "SubjectName", "SortOrder", "IsActive") VALUES (gen_random_uuid(), 'ISC', 'COMMERCE', 'Economics', 40, true);
INSERT INTO admissions.subjects_master ("Id", "BoardCode", "StreamCode", "SubjectName", "SortOrder", "IsActive") VALUES (gen_random_uuid(), 'ISC', 'COMMERCE', 'Mathematics', 50, true);
INSERT INTO admissions.subjects_master ("Id", "BoardCode", "StreamCode", "SubjectName", "SortOrder", "IsActive") VALUES (gen_random_uuid(), 'ISC', 'COMMERCE', 'Computer Science', 60, true);
INSERT INTO admissions.subjects_master ("Id", "BoardCode", "StreamCode", "SubjectName", "SortOrder", "IsActive") VALUES (gen_random_uuid(), 'ISC', 'COMMERCE', 'Business Studies', 70, true);
INSERT INTO admissions.subjects_master ("Id", "BoardCode", "StreamCode", "SubjectName", "SortOrder", "IsActive") VALUES (gen_random_uuid(), 'ISC', 'COMMERCE', 'Hindi', 80, true);

